# Build the package and publish it to PyPI after tests pass.
name: Publish to PyPI
on:
  push:
    tags:
      - "*"

jobs:
    
  publish:
    name: publish
    runs-on: [macos-latest, windows-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.0
      - name: Build package
        run: |
          python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_KEY }}
